# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)\alz'
    backendType: 'azurerm'
    backendServiceArm: 'Azure Landing Zone(ef620d24-2d5d-4e63-aaf9-e42cafb44dfb)'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'rg-alz-uks-01'
    backendAzureRmResourceGroupLocation: 'uksouth'
    backendAzureRmStorageAccountName: 'saalzuks01'
    backendAzureRmStorageAccountSku: 'Standard_LRS'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'alz1.tfstate'
    allowTelemetryCollection: true
    
- task: TerraformCLI@0
  inputs:
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)\alz'
    environmentServiceName: 'Azure Landing Zone(ef620d24-2d5d-4e63-aaf9-e42cafb44dfb)'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)\alz'
    environmentServiceName: 'Azure Landing Zone(ef620d24-2d5d-4e63-aaf9-e42cafb44dfb)'
    allowTelemetryCollection: true
